### ISSUE TITLE
basic_multi_ldap_auth_lock

### ISSUE THREAD

**Issue by cukal** [GuillaumeSmaha/ansible-role-gluu-configuration#1]
When checking the custom script basic_multi_ldap_auth_lock in Gluu Manage Custom Scripts the script shows this error:

```
org.xdi.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@212a8958'
	at org.xdi.service.PythonService.loadPythonScript(PythonService.java:182)
	at org.xdi.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source)
	at org.xdi.service.custom.script.CustomScriptManager.createExternalTypeFromStringWithPythonException(CustomScriptManager.java:372)
	at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.createExternalTypeFromStringWithPythonException(Unknown Source)
	at org.xdi.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:340)
	at org.xdi.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:253)
	at org.xdi.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:153)
	at org.xdi.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:141)
	at org.xdi.service.custom.script.CustomScriptManager.initTimer(CustomScriptManager.java:103)
	at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.initTimer$$super(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Traceback (most recent call last):
  File "basic_multi_ldap_auth_lock.py", line 1, in <module>
ImportError: No module named seam

	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.imp.import_logic(imp.java:913)
	at org.python.core.imp.import_module_level(imp.java:970)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1149)
	at org.python.core.imp.importFrom(imp.java:1124)
	at org.python.pycode._pyx0.f$0(basic_multi_ldap_auth_lock.py:21)
	at org.python.pycode._pyx0.call_function(basic_multi_ldap_auth_lock.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.xdi.service.PythonService.loadPythonScript(PythonService.java:179)
	... 18 more
```

**Comment by Yamilquery** [comment]
It seems that this repo doesn't have support.
It is a shame because this is pretty good!

**Comment by GuillaumeSmaha** [comment]
Sorry, I totally forgot to check about it.
It seems Gluu updates the dependencies and there is not `seam` anymore.

My script was based on https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/basic/BasicExternalAuthenticator.py

Using blame, I see `seam` was removed:
Before: https://github.com/GluuFederation/oxAuth/blame/61bddc9d758003f2834328c210f70f3c63f1c292/Server/integrations/basic/BasicExternalAuthenticator.py
After: https://github.com/GluuFederation/oxAuth/blame/6a8c229a8bae81418f7f020848e921904dda9878/Server/integrations/basic/BasicExternalAuthenticator.py

Also the import changed a lot of time and now it uses `org.gluu` instead of `org.xdi`
